### PR TITLE
workaround: disable steam to successfully build on GNU/Linux systems

### PR DESCRIPTION
**Pull request by M0Rf30**

### CODE REVIEW

**Comment by jjdredd** [comment]
I think I've tried this and the game was crashing.

**Comment by M0Rf30** [comment]
Yeah I agree with you @jjdredd  consider this not as fix but as a workaround. For now, at least on Arch Linux is working. maybe another temporary workaround would be reverting all the commits related to Steam, like:
- 55a02acf63ea0b148b52dd3b538d4238ff32a5a0
- a8f22d2d07e459b36f464f8378906dcfe25d2274

**Comment by xeome** [comment]
I can launch the game and use the realrtcw aur package, which contains this patch (afaik), but when I start a level, it crashes with the following error:
```ini
Sys_LoadGameDll(./main/qagame.sp.x86_64.so) failed:
"Failed loading ./main/qagame.sp.x86_64.so: ./main/qagame.sp.x86_64.so: undefined symbol: steamSetRichPresence"
----- Client Shutdown (Client fatal crashed: VM_Create on game failed) -----
```
@M0Rf30  Can you take a look at this? also, sha256 checksum for realrtcw-4.0.zip is incorrect.

**Comment by benjmarshall** [comment]
Hi @M0Rf30, your patch here is not working for me, either using the AUR PKGBUILD (which I think it yours?) or manually patching the github 4.0 tag. I have the same issue as @xeome above. The build completes succesfully but I can't start a level, or load a save game, or load any mods. Console output below:


```
Sys_LoadGameDll(./main/qagame.sp.x86_64.so) failed:
"Failed loading ./main/qagame.sp.x86_64.so: ./main/qagame.sp.x86_64.so: undefined symbol: steamSetRichPresence"
----- Client Shutdown (Client fatal crashed: VM_Create on game failed) -----
RE_Shutdown( 1 )
OpenAL capture device closed.
-----------------------
----- Server Shutdown (Server fatal crashed: VM_Create on game failed) -----
---------------------------
VM_Create on game failed
```
Do you see this in your builds? Any ideas what might cause this?

**Pull request closed without merging**
