### PR TITLE
fix linux build

### PR DESCRIPTION
**Pull request by jjdredd**

### CODE REVIEW

**Comment by wolfetplayer** [comment]
Can you explain?
I'm literally ZERO at anything related to linux

**Comment by jjdredd** [comment]
function va_arg() used at https://github.com/wolfetplayer/RealRTCW/pull/85/files#diff-f1546e5c1552cf01dc08d61ce69f8d4643710458b13b4d92f373476b9d58f2aeL58

in function `static void dbgpipe(const char *fmt, ...)`

is defined in stdarg.h:
https://man7.org/linux/man-pages/man3/va_arg.3p.html

**Comment by jjdredd** [comment]
=

**Comment by jjdredd** [comment]
I believe this file is related to steam integration code. Maybe it may be omitted at the stage of compilation for linux
(or whenever you don't want steam integration).

**Comment by M0Rf30** [comment]
Can confirm that this fix build on linux. together with
```
--- a/code/game/g_main.c        2022-08-14 10:45:34.000000000 +0200
+++ b/code/game/g_main.c        2022-08-19 14:37:51.620735638 +0200
@@ -30,7 +30,7 @@


 #include "g_local.h"
-#include "../../steam/steam.h"
+#include "../steam/steam.h"

 level_locals_t level;
```

**Comment by jjdredd** [comment]
@M0Rf30 I will recheck again later but I don't think I had to change path to `steam.h` in `g_main.c` to build the engine. Perhaps we were building with different options.

**Comment by M0Rf30** [comment]
here my build options
```
  USE_INTERNAL_LIBS=0 \
  COPYDIR=${pkgdir}/opt/realrtcw \
  make copyfiles
```
and I also use
`unset CFLAGS`
cause some warnings are treated as errors with default distro flags

**Comment by jjdredd** [comment]
I have just tested again: the game works fine on my intel video card, but when I try to use the nvidia video card, the menu freezes when I select  a savegame.

**Comment by M0Rf30** [comment]
Finally I managed to fix it. Seems to work like a charm.
Because I maintain the AUR package since 2.1, I also updated it.
Check it out for the patch
https://aur.archlinux.org/packages/realrtcw

**Comment by wolfetplayer** [comment]
Can you guys put together a final commit in this pull request?

**Comment by M0Rf30** [comment]
@wolfetplayer I can say from side that the only needed edits are the ones within this file
https://aur.archlinux.org/cgit/aur.git/plain/disable-steam.patch?h=realrtcw

and using the unset CFLAGS, because otherwise some warnings are treated as errors (cause of arch linux strict CFLAGS).

I refer to thiis error
```
CGAME_CC code/cgame/cg_main.c
code/cgame/cg_main.c: In function ‘CG_LoadTranslationTextStrings’:
code/cgame/cg_main.c:969:9: error: format not a string literal and no format arguments [-Werror=format-security]
  969 |         Com_sprintf(filename, MAX_QPATH, file);
      |         ^~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [Makefile:2923: build/release-linux-x86_64/main/cgame/cg_main.o] Errore 1
```
That's all from my side

**Pull request closed without merging**
